name: jitsi_meet_example
description: Demonstrates how to use the jitsi_meet plugin.
version: 0.1.2
publish_to: 'none'


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jitsi_meet:
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  google_fonts:
  provider:
  http: ^0.12.1
  image_picker:
  url_launcher:
  get_it: ^3.0.3
  flutter_native_html_view:
  path:
  file_picker:
  geolocator: ^5.1.3
  dio:
  charts_flutter:
  pin_code_text_field:
  flutter_rating_bar: ^3.0.1+1
  cloud_firestore: ^0.13.7
  flutter_launcher_icons: "^0.8.0"
  splashscreen: ^1.2.0
  shared_preferences: ^0.5.12+2
  intl: ^0.16.1
  permission_handler: '^4.4.0+hotfix.2'
  firebase_storage:  ^3.0.3
  connectivity: ^2.0.2


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"
    

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family: MyFlutterApp1
      fonts:
        - asset: assets/fonts/MyFlutterApp1.ttf

    - family: MyFlutterApp2
      fonts:
         - asset: assets/fonts/MyFlutterApp2.ttf
  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
